# Generated by Django 5.2.6 on 2025-09-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookslending',
            old_name='bookId',
            new_name='book',
        ),
    ]
