# Generated by Django 5.2.6 on 2025-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberships',
            name='dob',
            field=models.DateField(default='2002-10-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='profile',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
