# Generated by Django 5.2.6 on 2025-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0002_books_category_remove_user_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='unique_code',
        ),
        migrations.AlterField(
            model_name='books',
            name='available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
