# Generated by Django 5.2.6 on 2025-09-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0002_rename_bookid_bookslending_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookslending',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Redstar.memberships'),
        ),
    ]
