# Generated by Django 5.2.6 on 2025-09-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0003_remove_inventory_unique_code_alter_books_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='available',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total',
        ),
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
