# Generated by Django 5.2.6 on 2025-09-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0004_remove_inventory_available_remove_inventory_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Inventory_images/'),
        ),
    ]
