# Generated by Django 5.2.6 on 2025-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0005_remove_inventory_image_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
