# Generated by Django 5.2.6 on 2025-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Category_images/'),
        ),
    ]
