# Generated by Django 5.2.6 on 2025-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylending',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
