# Generated by Django 5.2.6 on 2025-09-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0009_alter_inventorylending_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylending',
            old_name='lended_date',
            new_name='lendedDate',
        ),
        migrations.RenameField(
            model_name='inventorylending',
            old_name='mobile_number',
            new_name='mobileNumber',
        ),
        migrations.RenameField(
            model_name='inventorylending',
            old_name='return_date',
            new_name='returnDate',
        ),
    ]
