# Generated by Django 5.2.6 on 2025-09-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0010_rename_lended_date_inventorylending_lendeddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='available',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='Redstar.category'),
        ),
    ]
