# Generated by Django 5.2.6 on 2025-09-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0011_remove_books_available_alter_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available',
        ),
    ]
