# Generated by Django 5.2.6 on 2025-09-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0012_remove_category_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total',
        ),
    ]
