# Generated by Django 5.2.6 on 2025-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0013_remove_category_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
