# Generated by Django 5.2.6 on 2025-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0014_books_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membershipId', models.TextField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('profile', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('mobileNumber', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
