# Generated by Django 5.2.6 on 2025-09-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0015_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='address',
            field=models.CharField(max_length=15),
        ),
    ]
