# Generated by Django 5.2.6 on 2025-09-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0016_alter_memberships_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='profile',
        ),
        migrations.AddField(
            model_name='memberships',
            name='profil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='mobileNumber',
            field=models.CharField(max_length=15),
        ),
    ]
