# Generated by Django 5.2.6 on 2025-09-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redstar', '0017_remove_memberships_profile_memberships_profil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberships',
            old_name='profil',
            new_name='profile',
        ),
    ]
